title: Hello, world! I'm Deividy Negri
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "deividynegri.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Deividy negri # add your name
author-img: deividy-negri.png # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-github: deividynegri # add your Github handle
social-linkedin: deividy-negri-00927462 # add your Linkedin handle
social-email: deividy.n@gmail.com # add your Email address

# Disqus
discus-identifier: deividynegri-github-io # add your discus identifier

# Tracker
analytics: UA-53659726-10 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
